language: python
python:
  - "3.6.4"
  
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install coveralls
script:
  - python -m pytest --cov-report term-missing --cov=resources
before_script:
  - source ./.travis.sh
  - psql -c 'create database travis_tests;' -U postgres
after_success:
  - coveralls
notifications:
  email: false
