language: python
python:
  - "3.6.4"
  
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install coveralls
script:
  - "python tests/test_users.py"
  - "python tests/test_meals.py"
after_success:
  - coveralls
notifications:
  email: false
